name: Release Test

on:
  release

jobs:
  job_release:
    name: Release Job
    runs-on: ["ubuntu-latest"]
    steps:
      - run: echo "event name is:" ${{ github.event_name }}
      - run: echo "event type is:" ${{ github.event.action }}
      - run: echo "GITHUB_REF_NAME is:" $GITHUB_REF_NAME
      - run: echo "GITHUB_SHA is:" $GITHUB_SHA