name: Resuable Workflow

on:
  workflow_call:

jobs:
  job-test-in-resuable:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Enable workflow
        run: |
          WORKFLOW_NAME="${{ github.workflow }}"
          WORKFLOW_ID=$(gh workflow list | grep "$WORKFLOW_NAME" | awk '{print $3}')
          gh workflow enable $WORKFLOW_ID
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
