name: Test Workflow

on:
  push

env:
  FOO: ${{ secrets.ACTION_REPO_FOO }}

jobs:
  print-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print github.workflow
        run: echo "github.workflow is ${{ github.workflow }}"
