name: World

on:
  schedule:
    - cron: '50 16 * * *'

jobs:
  job-run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Run the script
        run: |
          node -e "console.log('The run-script job in World workflow runs at', new Date)"
          date +%Z
